In [1]:
#import packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
#import median household income data for Albany Park

income_Albany_Park=pd.read_csv('median Household income/Albany_Park_Median_Household_Income.csv')

In [11]:
income_Albany_Park

,Category,Full population,Full population CI (low),Full population CI (high)
0,2006-2010,68196.912310,62664.945288,73728.879337
1,2007-2011,65726.514266,61105.020942,70348.007590
2,2008-2012,66277.496234,61434.068040,71120.924427
3,2009-2013,68956.558798,63998.520418,73914.597178
4,2010-2014,73910.616391,66558.443814,81262.788969
5,2011-2015,73135.052483,66050.467244,80219.637721
6,2012-2016,76593.809969,70482.971010,82704.648932
7,2013-2017,78001.900110,71227.328758,84776.471462
8,2014-2018,76691.290769,68648.970970,84733.610568
9,2015-2019,79134.474530,71895.465508,86373.483553
10,2016-2020,84572.844797,75072.587745,94073.101850
11,2017-2021,83232.060261,73868.665413,92595.455108
12,2018-2022,84276.043977,74904.058242,93648.029710
13,2019-2023,86061.871429,76310.666715,95813.076142
14,2020-2024,87083.511757,77020.478173,97146.545341

The data is like a time seriex, except the time stamps are 5 year periods that overlap 4 years from one data point to the next. I'm not sure how to handle this.

The data also comes with a confidence interval. I'm not sure if we need this or not.

In [12]:
#reading in housing properties sales activity for Albany Park

sales_Albany_Park=pd.read_csv('Housing Properties Sales Activity/Albany_Park_Housing_Sales_Count.csv')

In [13]:
sales_Albany_Park

    Category  Full population
0       2009              295
1       2010              328
2       2011              309
3       2012              381
4       2013              437
5       2014              413
6       2015              446
7       2016              517
8       2017              478
9       2018              450
10      2019              408
11      2020              412
12      2021              593
13      2022              448
14      2023              357

The housing sales data is a time series with new housing sales per year. This data's time stamp structure is different from the income data.